# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_npoP0LCWSiEl6-xz3nnfwMywt-lHHQf
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# 
# from rental import Vehicle, Renter, ElectricCar, Motorbike
# 
# print("=== CampusWheels Vehicle Rental ===")
# 
# car = Vehicle("Toyota", "Yaris", "1AB234")
# electric_car = ElectricCar("Tesla", "Model 3", "2EV567", 75)
# motorbike = Motorbike("Honda", "Click", "3MB890", 125)
# 
# renter = Renter("John", 12345)
# 
# print("\nVehicles:")
# print(car)
# print(electric_car)
# print(motorbike)
# 
# print("\nRenting Toyota Yaris...")
# car.rent()
# renter.rented.append(car)
# print(car)
# 
# print("\nReturning Toyota Yaris...")
# car.return_vehicle()
# renter.rented.remove(car)
# print(car)
# 
# print("\nTesting invalid renter name...")
# 
# try:
#     bad_renter = Renter("", 12345)
# except ValueError as e:
#     print("ValueError caught:", e)
# 
# print("\nTesting invalid license number...")
# 
# try:
#     bad_renter = Renter("Alice", 0)
# except ValueError as e:
#     print("ValueError caught:", e)
# 
# print("\nTesting property validation...")
# 
# try:
#     renter.name = ""
# except ValueError as e:
#     print("ValueError caught:", e)
# 
# try:
#     renter.license_no = -10
# except ValueError as e:
#     print("ValueError caught:", e)
# 
# print("\n=== Polymorphism Test ===")
# 
# vehicles = [
#     Vehicle("Toyota", "Yaris", "1AB234"),
#     ElectricCar("Tesla", "Model 3", "2EV567", 75),
#     Motorbike("Honda", "Click", "3MB890", 125)
# ]
# 
# for vehicle in vehicles:
#     print(vehicle)
